# Generated by Django 2.0.9 on 2019-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190115_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='img',
            field=models.ImageField(default='no-img', upload_to='image'),
            preserve_default=False,
        ),
    ]
